### ISSUE TITLE
Request - Trained weights

### ISSUE THREAD

**Issue by ofirkris** [YangNaruto/FQ-GAN#1]
Hello, thanks for sharing your research.
I'm studying Style transfer and would like to test with your trained weights, can you be so kind and share them?

**Comment by ChunyuanLI** [comment]
Which model trained on which dataset do you specifically need?

**Comment by ofirkris** [comment]
Photo2portrait + Selfie2AnimeSelfie2Anime - Thanks!
My email - ofirseo AT gmail.com

**Comment by ghost** [comment]
@ChunyuanLI can you please upload the weights to google drive and share the link in the repo?

**Comment by YangNaruto** [comment]
Sure, I will share the checkpoint. Please wait a little while.

**Comment by YangNaruto** [comment]
> Photo2portrait + Selfie2AnimeSelfie2Anime - Thanks!
> My email - ofirseo AT gmail.com

**Comment by YangNaruto** [comment]
> Photo2portrait + Selfie2AnimeSelfie2Anime - Thanks!
> My email - ofirseo AT gmail.com

Here is the pre-trained model for [photo2portrait](https://drive.google.com/drive/folders/1hE8p0CcsQOvOtbVzoBql0wsdtsMgFvEZ?usp=sharing)
For selfie2anime, uploaded.
