### ISSUE TITLE
use quantized or not?

### ISSUE THREAD

**Issue by jayzhan211** [YangNaruto/FQ-GAN#2]
https://github.com/YangNaruto/FQ-GAN/blob/3bc3ee25f4d4ad8934acd37ff3d0c0c4a785d5b6/FQ-U-GAT-IT/vq_layer.py#L108

https://github.com/YangNaruto/FQ-GAN/blob/3bc3ee25f4d4ad8934acd37ff3d0c0c4a785d5b6/FQ-U-GAT-IT/vq_layer.py#L104

you return `loss`, `perplexity`  but not `quantized` in Line 104, is it better to not use the quantized_x and only compute the `quant_loss`?

https://github.com/YangNaruto/FQ-GAN/blob/3bc3ee25f4d4ad8934acd37ff3d0c0c4a785d5b6/FQ-U-GAT-IT/UGATIT.py#L259-L269

**Comment by YangNaruto** [comment]
Nice question! The loss term acts as an implicit feature matching regularizer as demonstrated in the paper. In practice, we find that 1) the GAN training can benefit from this loss term; 2) When the quantized is returned and inputs to the next layer, parameters of the dictionary need an elaborate tuning. A warmup stage is sometimes designed to make sure the dictionary can catch up with the GAN training. This version's code is to make sure everyone can get expected and fancy GAN models without tuning anything.
