### ISSUE TITLE
A better Colab?

### ISSUE THREAD

**Issue by nerdogram** [YangNaruto/FQ-GAN#6]
Hi - great work on this but can you make a better Colab version that's more end to end and can run without the user having to move datasets and models to the right place on their own? Preferably with the option to run inference on a custom image.

**Comment by YangNaruto** [comment]
Sure. Please wait a little while

**Comment by theyellowdiary** [comment]
@YangNaruto updates?

**Comment by YangNaruto** [comment]
> @YangNaruto updates?

Sorry. Currently, I have an urgent deadline. I will finish it by next month.

**Comment by ChunyuanLI** [comment]
[`Selfie2Anime Demo`](http://40.71.23.172:8888/)  is released. Try it out.

**Comment by ghost** [comment]
@ChunyuanLI the current demo only shows one output image if the face is not detected and it seems to be from another user, maybe you need a unique identifier for each request. I can help with that if needed

**Comment by ChunyuanLI** [comment]
Thanks for the quick response. I added a time identifier for file to track its processing. It should be okay now.
